version: '3.8'

services:
  weglow-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weglow-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - weglow

  weglow-server:
    image: nginx:alpine
    container_name: weglow-server
    restart: unless-stopped
    ports:
      - "8080:80"  # локальный порт для iOS/Flutter
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - weglow-app
    networks:
      - weglow

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: weglow
      POSTGRES_USER: weglow
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weglow

volumes:
  pgdata:

networks:
  weglow:
    driver: bridge
