version: '3.8'

services:
  weglow-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weglow-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    networks:
      - weglow

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: weglow
      POSTGRES_USER: weglow
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weglow

volumes:
  pgdata:

networks:
  weglow:
    driver: bridge
